package com.bce.demo.controllers.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "usuario")

public class User {

    @Id
    @GeneratedValue

    private int id;
    private String name;
    private String address;
    private String phone;

    // Constructor, getters, setters, etc. can be generated by Lombok annotations

}
